import { Player, Team, ScoutingReport, UserProfile, RankingList, TeamReport } from '../types';

export const mockUser: UserProfile = {
  id: 'usr_1',
  email: 'chief_scout@ctsn.club',
  name: 'Santiago Bernabéu',
  role: 'head_scout',
  clubId: 'club_1',
  avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
  createdAt: '2026-01-01T12:00:00Z',
};

export const mockTeams: Team[] = [
  {
    id: 'team_1',
    name: 'Real Madrid CF',
    league: 'La Liga',
    country: 'Spain',
    logoUrl: 'https://images.unsplash.com/photo-1628157582853-a796fa650a6a?auto=format&fit=crop&w=128&h=128&q=80',
    clubId: 'club_1',
    scoutId: 'usr_1',
    playersCount: 25,
    season: '2025/2026',
    coach: 'Carlo Ancelotti',
    usualSystem: '4-3-1-2',
    gameModel: 'Modelo híbrido vertical y asociativo, con gran libertad creativa para mediapuntas e interiores en ataque organizado.',
    pressingStyle: 'Bloque medio-bajo muy organizado con presión selectiva y agresiva en zona activa de balón.',
    buildUp: 'Salida limpia con pivote descolgándose entre centrales, apoyándose en la proyección ofensiva de los laterales.',
    transitions: 'Contraataques veloces explotando la velocidad de los extremos y el juego asociativo en transiciones rápidas.',
    setPieces: 'Centros en rosca al punto de penalti en córners ofensivos; marcaje mixto en fase defensiva.',
    collectiveStats: {
      matchesPlayed: 38,
      won: 29,
      drawn: 7,
      lost: 2,
      goalsFor: 87,
      goalsAgainst: 26,
      cleanSheets: 18,
    },
    seasonHistory: [
      { season: '2024/2025', leaguePosition: 1, coach: 'Carlo Ancelotti' },
      { season: '2023/2024', leaguePosition: 1, coach: 'Carlo Ancelotti' },
    ],
    createdAt: '2026-01-01T12:00:00Z',
  },
  {
    id: 'team_2',
    name: 'Manchester City FC',
    league: 'Premier League',
    country: 'England',
    logoUrl: 'https://images.unsplash.com/photo-1606041008023-472dfb5e530f?auto=format&fit=crop&w=128&h=128&q=80',
    clubId: 'club_1',
    scoutId: 'usr_1',
    playersCount: 23,
    season: '2025/2026',
    coach: 'Pep Guardiola',
    usualSystem: '3-2-4-1',
    gameModel: 'Juego de posición estricto, posesión alta, control del ritmo de juego y sobrecarga en pasillos interiores.',
    pressingStyle: 'Presión alta asfixiante inmediata en campo contrario tras pérdida del balón.',
    buildUp: 'Salida de 3 con laterales que se interiorizan como pivotes creando superioridad numérica en la medular.',
    transitions: 'Transición defensiva inmediata mediante acoso inmediato o faltas tácticas preventivas.',
    setPieces: 'Jugadas ensayadas en córners, bloqueos en área chica y saques de falta con centros bombeados al segundo palo.',
    collectiveStats: {
      matchesPlayed: 38,
      won: 28,
      drawn: 7,
      lost: 3,
      goalsFor: 96,
      goalsAgainst: 34,
      cleanSheets: 15,
    },
    seasonHistory: [
      { season: '2024/2025', leaguePosition: 2, coach: 'Pep Guardiola' },
      { season: '2023/2024', leaguePosition: 1, coach: 'Pep Guardiola' },
    ],
    createdAt: '2026-01-01T12:00:00Z',
  },
  {
    id: 'team_3',
    name: 'FC Bayern München',
    league: 'Bundesliga',
    country: 'Germany',
    logoUrl: 'https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?auto=format&fit=crop&w=128&h=128&q=80',
    clubId: 'club_1',
    scoutId: 'usr_1',
    playersCount: 22,
    season: '2025/2026',
    coach: 'Vincent Kompany',
    usualSystem: '4-2-3-1',
    gameModel: 'Fútbol ofensivo expansivo de mucha amplitud por bandas con extremos puros y juego vertical rápido.',
    pressingStyle: 'Presión alta hombre a hombre asumiendo riesgos elevados con línea defensiva muy adelantada.',
    buildUp: 'Salida limpia buscando asociaciones de pivotes y descargas rápidas en amplitud.',
    transitions: 'Ataques veloces en transiciones rápidas verticales por bandas en pocos toques.',
    setPieces: 'Centros en rosca al punto de penalti en córners ofensivos; marcaje mixto en fase defensiva.',
    collectiveStats: {
      matchesPlayed: 34,
      won: 25,
      drawn: 5,
      lost: 4,
      goalsFor: 89,
      goalsAgainst: 31,
      cleanSheets: 13,
    },
    seasonHistory: [
      { season: '2024/2025', leaguePosition: 1, coach: 'Vincent Kompany' },
      { season: '2023/2024', leaguePosition: 3, coach: 'Thomas Tuchel' },
    ],
    createdAt: '2026-01-01T12:00:00Z',
  },
];

export const mockPlayers: Player[] = [
  {
    id: 'ply_1',
    name: 'Jude Bellingham',
    age: 23,
    nationality: 'England',
    club: 'Real Madrid CF',
    position: 'AM',
    preferredFoot: 'Right',
    height: 186,
    weight: 75,
    contractUntil: '2029-06-30',
    marketValue: 180000000,
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=facearea&facepad=2.2&w=256&h=256&q=80',
    rating: 5,
    potential: 5.0,
    status: 'Target',
    attributes: {
      pace: 84,
      shooting: 86,
      passing: 88,
      dribbling: 90,
      defending: 78,
      physical: 89,
      tactical: 92,
    },
    stats: {
      matchesPlayed: 28,
      minutesPlayed: 2320,
      goals: 19,
      assists: 6,
      yellowCards: 5,
      redCards: 0,
    },
    scoutId: 'usr_1',
    clubId: 'club_1',
    createdAt: '2026-02-10T14:30:00Z',
    updatedAt: '2026-06-25T11:20:00Z',
  },
  {
    id: 'ply_2',
    name: 'Erling Haaland',
    age: 25,
    nationality: 'Norway',
    club: 'Manchester City FC',
    position: 'ST',
    preferredFoot: 'Left',
    height: 194,
    weight: 88,
    contractUntil: '2027-06-30',
    marketValue: 180000000,
    photoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
    rating: 5,
    potential: 5.0,
    status: 'Monitored',
    attributes: {
      pace: 93,
      shooting: 96,
      passing: 75,
      dribbling: 82,
      defending: 45,
      physical: 92,
      tactical: 88,
    },
    stats: {
      matchesPlayed: 34,
      minutesPlayed: 2950,
      goals: 36,
      assists: 8,
      yellowCards: 3,
      redCards: 0,
    },
    scoutId: 'usr_1',
    clubId: 'club_1',
    createdAt: '2026-02-15T09:15:00Z',
    updatedAt: '2026-06-20T17:45:00Z',
  },
  {
    id: 'ply_3',
    name: 'Florian Wirtz',
    age: 23,
    nationality: 'Germany',
    club: 'Bayer 04 Leverkusen',
    position: 'AM',
    preferredFoot: 'Right',
    height: 176,
    weight: 72,
    contractUntil: '2027-06-30',
    marketValue: 130000000,
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
    rating: 4.8,
    potential: 4.9,
    status: 'Recommended',
    attributes: {
      pace: 81,
      shooting: 83,
      passing: 92,
      dribbling: 94,
      defending: 58,
      physical: 72,
      tactical: 94,
    },
    stats: {
      matchesPlayed: 32,
      minutesPlayed: 2640,
      goals: 14,
      assists: 18,
      yellowCards: 2,
      redCards: 0,
    },
    scoutId: 'usr_1',
    clubId: 'club_1',
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-06-28T15:30:00Z',
  },
  {
    id: 'ply_4',
    name: 'William Saliba',
    age: 25,
    nationality: 'France',
    club: 'Arsenal FC',
    position: 'CB',
    preferredFoot: 'Right',
    height: 192,
    weight: 85,
    contractUntil: '2028-06-30',
    marketValue: 80000000,
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
    rating: 4.7,
    potential: 4.9,
    status: 'Target',
    attributes: {
      pace: 82,
      shooting: 40,
      passing: 79,
      dribbling: 74,
      defending: 92,
      physical: 86,
      tactical: 90,
    },
    stats: {
      matchesPlayed: 35,
      minutesPlayed: 3150,
      goals: 2,
      assists: 1,
      yellowCards: 4,
      redCards: 1,
    },
    scoutId: 'usr_1',
    clubId: 'club_1',
    createdAt: '2026-03-10T16:20:00Z',
    updatedAt: '2026-06-18T09:10:00Z',
  },
  {
    id: 'ply_5',
    name: 'Eduardo Camavinga',
    age: 23,
    nationality: 'France',
    club: 'Real Madrid CF',
    position: 'DM',
    preferredFoot: 'Left',
    height: 182,
    weight: 74,
    contractUntil: '2029-06-30',
    marketValue: 90000000,
    photoUrl: 'https://images.unsplash.com/photo-1624561172888-ac93c696e10c?auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
    rating: 4.6,
    potential: 4.8,
    status: 'Monitored',
    attributes: {
      pace: 82,
      shooting: 72,
      passing: 84,
      dribbling: 87,
      defending: 82,
      physical: 83,
      tactical: 85,
    },
    stats: {
      matchesPlayed: 30,
      minutesPlayed: 2100,
      goals: 1,
      assists: 3,
      yellowCards: 7,
      redCards: 0,
    },
    scoutId: 'usr_1',
    clubId: 'club_1',
    createdAt: '2026-04-02T11:00:00Z',
    updatedAt: '2026-06-22T14:15:00Z',
  },
];

export const mockReports: ScoutingReport[] = [
  {
    id: 'rep_1',
    playerId: 'ply_1',
    playerName: 'Jude Bellingham',
    playerPhotoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=facearea&facepad=2.2&w=256&h=256&q=80',
    playerPosition: 'AM',
    scoutId: 'usr_1',
    scoutName: 'Santiago Bernabéu',
    matchName: 'Real Madrid vs Barcelona (El Clásico)',
    matchDate: '2026-04-21',
    notes: 'Rendimiento espectacular en la mediapunta. Dominó el espacio entre líneas, ofreciendo siempre una línea de pase limpia. Convirtió un gol tras una llegada al segundo palo y asistió en el segundo. Físicamente imponente en duelos individuales y tácticamente maduro cubriendo las transiciones defensivas del rival.',
    strengths: ['Llegada de segunda línea', 'Físico imponente', 'Visión de juego', 'Presión tras pérdida'],
    weaknesses: ['Ansiedad en el repliegue tardío', 'Propenso a protestar faltas'],
    verdict: 'Sign',
    rating: 9.5,
    createdAt: '2026-04-22T10:00:00Z',
    updatedAt: '2026-04-22T10:30:00Z',
  },
  {
    id: 'rep_2',
    playerId: 'ply_3',
    playerName: 'Florian Wirtz',
    playerPhotoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
    playerPosition: 'AM',
    scoutId: 'usr_1',
    scoutName: 'Santiago Bernabéu',
    matchName: 'Bayer Leverkusen vs Bayern München',
    matchDate: '2026-05-12',
    notes: 'Impresionante lectura de juego y giros en espacios reducidos. Control orientado de clase mundial. Destaca por su capacidad para filtrar pases decisivos. En defensa trabaja de forma organizada en el bloque medio del equipo, aunque le falta algo de fuerza en disputas de hombro a hombro contra pivotes robustos.',
    strengths: ['Giros en espacio reducido', 'Pase filtrado', 'Creatividad', 'Control orientado'],
    weaknesses: ['Duelos físicos aéreos', 'Velocidad punta en distancias largas'],
    verdict: 'Sign',
    rating: 9.0,
    createdAt: '2026-05-13T14:20:00Z',
    updatedAt: '2026-05-13T14:20:00Z',
  },
  {
    id: 'rep_3',
    playerId: 'ply_4',
    playerName: 'William Saliba',
    playerPhotoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
    playerPosition: 'CB',
    scoutId: 'usr_1',
    scoutName: 'Santiago Bernabéu',
    matchName: 'Arsenal vs Manchester City',
    matchDate: '2026-05-24',
    notes: 'Excelente partido defendiendo a Erling Haaland. Mantuvo la línea defensiva muy alta y concentrada. Ganó el 80% de los duelos terrestres y mostró compostura absoluta en la salida de balón bajo presión alta. Inteligente para anticiparse a los desmarques.',
    strengths: ['Anticipación', 'Salida de balón bajo presión', '1v1 defensivo', 'Velocidad de recuperación'],
    weaknesses: ['A veces demasiado paciente en la entrada directa'],
    verdict: 'Sign',
    rating: 8.8,
    createdAt: '2026-05-25T09:40:00Z',
    updatedAt: '2026-05-25T09:40:00Z',
  },
];

export const mockRankings: RankingList[] = [
  {
    id: 'rnk_1',
    name: 'Top Talentos Sub-25 2026',
    description: 'Los jugadores menores de 25 años más seguidos por la dirección deportiva para reforzar el mediocampo y la delantera.',
    clubId: 'club_1',
    playerIds: ['ply_1', 'ply_3', 'ply_2', 'ply_5'],
    createdAt: '2026-06-01T08:00:00Z',
  },
  {
    id: 'rnk_2',
    name: 'Prioridades Defensa Central',
    description: 'Búsqueda de centrales con gran salida de balón y velocidad para jugar con bloque alto.',
    clubId: 'club_1',
    playerIds: ['ply_4'],
    createdAt: '2026-06-15T12:00:00Z',
  },
];

export const mockTeamReports: TeamReport[] = [
  {
    id: 'rep_t_1',
    teamId: 'team_1',
    scoutId: 'usr_1',
    scoutName: 'Santiago Bernabéu',
    date: '2026-06-10',
    notes: 'Real Madrid CF presenta un bloque defensivo extremadamente sólido bajo la dirección de Ancelotti. Su transición ofensiva es letal gracias a la zancada rápida de sus atacantes. Muestran paciencia táctica replegando en bloque medio.',
    verdict: 'Excellent',
    tacticalAnalysis: 'El sistema 4-3-1-2 se convierte en rombo dinámico. El mediocampista ofensivo actúa como conector principal en transiciones rápidas.',
    strengths: ['Velocidad en contragolpe', 'Polivalencia en el mediocampo', 'Jerarquía individual en momentos clave'],
    weaknesses: ['Vulnerable a espaldas de laterales muy adelantados', 'Dependencia de la creatividad individual ante bloques muy cerrados'],
    createdAt: '2026-06-10T14:00:00Z',
  },
];
